### ISSUE TITLE
Document -oracle vs -bridge options?

### ISSUE THREAD

**Issue by wrouesnel** [coreos/zetcd#21]
Neither of these two options are really documented by their command line help nor anywhere else I can see at the moment. Is there a clearer explanation of what they do?

**Comment by heyitsanthony** [comment]
I realized I didn't provide an explanation but you may be interested regardless:

`-zkbridge` is the client address of what is considered a 'bonafide' zookeeper server (this can be a zetcd server too, but usually it's an actual zk server). It is used for cross checking when `-oracle` is given (comparing two server responses in lock-step) and testing protocol serialization/deserialization otherwise (zetcd will act as a proxy that will forward requests to another zk server).

`-oracle` accepts either `etcd` or `zk`; this chooses between treating the `zetcd` responses as ground truth or the `zkbridge` as ground truth when cross-checking. This is mostly important for selecting which server response to return in cases where the zetcd result can't reasonably be expected to perfectly match a zk response (e.g., znode mtime).
